### ISSUE TITLE
test.so build faled

### ISSUE THREAD

**Issue by Boom-Hacker** [ROCmSoftwarePlatform/AITemplate#71]
2023-09-17 19:02:48,710 INFO <aitemplate.backend.codegen> generated 207 function srcs
2023-09-17 19:02:50,015 INFO <aitemplate.backend.codegen> generated 8 library srcs
2023-09-17 19:02:50,015 INFO <aitemplate.backend.builder> Using 16 CPU for building
2023-09-17 19:07:31,399 INFO <aitemplate.compiler.compiler> compiled the final .so file elapsed time: 0:04:41.384353
[19:07:31] model_container.cpp:67: Device Runtime Version: 50422803; Driver Version: 50422803
[19:07:31] model_container.cpp:81: Hardware accelerator device properties: 
  Device: 
     ASCII string identifying device: AMD Radeon RX 6750 XT
     Major compute capability: 10
     Minor compute capability: 3
     AMD GCN Arch Value: 1030
     PCI bus ID of the device: 3
     PCI device ID of the device: 0
  Memory limits: 
     Constant memory available on device in bytes: 2147483647
     Global memory available on device in bytes: 12868124672
     Global memory bus width in bits: 192
     Size of L2 cache in bytes: 3145728
     Shared memory available per block in bytes: 65536
     Maximum Shared Memory Per Multiprocessor in bytes: 65536
[19:07:31] model_container.cpp:85: Init AITemplate Runtime with 1 concurrency
Traceback (most recent call last):
  File "/home/beforespace/AITnew/AITemplate/examples/05_stable_diffusion/scripts/compile.py", line 106, in <module>
    compile_diffusers()
  File "/home/beforespace/AITnew/AITemplate/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/beforespace/AITnew/AITemplate/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/beforespace/AITnew/AITemplate/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/beforespace/AITnew/AITemplate/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/beforespace/AITnew/AITemplate/examples/05_stable_diffusion/scripts/compile.py", line 95, in compile_diffusers
    compile_vae(
  File "/home/beforespace/AITnew/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_vae.py", line 128, in compile_vae
    params_ait = map_vae_params(ait_vae, pt_mod, batch_size, height * width)
  File "/home/beforespace/AITnew/AITemplate/examples/05_stable_diffusion/src/compile_lib/compile_vae.py", line 48, in map_vae_params
    q_weight = pt_params[prefix + "query.weight"]
KeyError: 'decoder.mid_block.attentions.0.query.weight'

**Comment by Boom-Hacker** [comment]
use special version of diffusers and transformers,in 05 stable diffusion 's readme.md
