### ISSUE TITLE
<class 'src.pipeline_stable_diffusion_ait.StableDiffusionAITPipeline'> is incorrectly implemented. Expected {'feature_extractor', 'scheduler', 'tokenizer', 'text_encoder', 'safety_checker', 'unet', 'vae'} to be defined

### ISSUE THREAD

**Issue by jiagaoxiang** [ROCmSoftwarePlatform/AITemplate#80]
Run this line of code:
python3 scripts/demo.py --prompt "Mountain Rainier in van Gogh's world"

Got the following errors:

[20:11:19] model_container.cpp:87: Init AITemplate Runtime with 1 concurrency
Traceback (most recent call last):
File "/home/aac/AITemplate/examples/05_stable_diffusion/scripts/demo.py", line 66, in
run()
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/click/core.py", line 1157, in call
return self.main(*args, **kwargs)
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "/home/aac/AITemplate/examples/05_stable_diffusion/scripts/demo.py", line 51, in run
).to("cuda")
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 832, in to
module_is_sequentially_offloaded(module) for _, module in self.components.items()
File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1954, in components
raise ValueError(
ValueError: StableDiffusionAITPipeline {
"_class_name": "StableDiffusionAITPipeline",
"_diffusers_version": "0.24.0",
"_name_or_path": "./tmp/diffusers-pipeline/stabilityai/stable-diffusion-v2",
"feature_extractor": [
"transformers",
"CLIPFeatureExtractor"
],
"image_encoder": [
null,
null
],
"requires_safety_checker": true,
"safety_checker": [
"stable_diffusion",
"StableDiffusionSafetyChecker"
],
"scheduler": [
"diffusers",
"EulerDiscreteScheduler"
],
"text_encoder": [
"transformers",
"CLIPTextModel"
],
"tokenizer": [
"transformers",
"CLIPTokenizer"
],
"unet": [
"diffusers",
"UNet2DConditionModel"
],
"vae": [
"diffusers",
"AutoencoderKL"
]
}
has been incorrectly initialized or <class 'src.pipeline_stable_diffusion_ait.StableDiffusionAITPipeline'> is incorrectly implemented. Expected {'feature_extractor', 'scheduler', 'tokenizer', 'text_encoder', 'safety_checker', 'unet', 'vae'} to be defined, but dict_keys(['vae', 'text_encoder', 'tokenizer', 'unet', 'scheduler', 'safety_checker', 'feature_extractor', 'image_encoder']) are defined.

**Comment by fsx950223** [comment]
You should use diffusers==0.11.1 version on README.

**Comment by Boom-Hacker** [comment]
> You should use diffusers==0.11.1 version on README.

can you reply my email?
