### ISSUE TITLE
build dymanic failed

### ISSUE THREAD

**Issue by Boom-Hacker** [ROCmSoftwarePlatform/AITemplate#81]
INFO:aitemplate.backend.build_cache_base:Build cache disabled 2023-12-24 09:52:06,694 INFO <aitemplate.testing.detect_target> Set target to ROCM Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.86it/s] Traceback (most recent call last):   File "./scripts/compile_alt.py", line 138, in <module>     compile_diffusers()   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__     return self.main(*args, **kwargs)   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main     rv = self.invoke(ctx)   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke     return ctx.invoke(self.callback, **ctx.params)   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke     return __callback(*args, **kwargs)   File "./scripts/compile_alt.py", line 98, in compile_diffusers     compile_clip(   File "/root/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion/src/compile_lib/compile_clip_alt.py", line 82, in compile_clip     Y = ait_mod(input_ids=input_ids_ait, position_ids=position_ids_ait)   File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/module.py", line 389, in _call_impl     return forward_call(*input, **kwargs)   File "/root/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion/src/modeling/clip.py", line 676, in forward     encoder_outputs = self.encoder(   File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/module.py", line 389, in _call_impl     return forward_call(*input, **kwargs)   File "/root/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion/src/modeling/clip.py", line 556, in forward     layer_outputs = encoder_layer(hidden_states)   File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/module.py", line 389, in _call_impl     return forward_call(*input, **kwargs)   File "/root/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion/src/modeling/clip.py", line 451, in forward     hidden_states = self.self_attn(   File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/module.py", line 389, in _call_impl     return forward_call(*input, **kwargs)   File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/attention.py", line 410, in forward     assert len(args) >= 3 AssertionError

**Comment by Boom-Hacker** [comment]
if i use multiheadattention:


root@localhost-live:~/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion# python3 ./scripts/compile_alt.py INFO:aitemplate.backend.build_cache_base:Build cache disabled
2023-12-24 10:10:28,830 INFO <aitemplate.testing.detect_target> Set target to ROCM
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  6.75it/s]
Traceback (most recent call last):
  File "./scripts/compile_alt.py", line 138, in <module>
    compile_diffusers()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "./scripts/compile_alt.py", line 98, in compile_diffusers
    compile_clip(
  File "/root/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion/src/compile_lib/compile_clip_alt.py", line 60, in compile_clip
    ait_mod = ait_CLIPTextTransformer(
  File "/root/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion/src/modeling/clip.py", line 633, in __init__
    self.encoder = CLIPEncoder(
  File "/root/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion/src/modeling/clip.py", line 488, in __init__
    [
  File "/root/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion/src/modeling/clip.py", line 489, in <listcomp>
    CLIPEncoderLayer(
  File "/root/mergingtest8/AITemplate-navi3_new/examples/05_stable_diffusion/src/modeling/clip.py", line 405, in __init__
    self.self_attn = nn.MultiheadAttention(
  File "/usr/local/lib/python3.8/dist-packages/aitemplate/frontend/nn/attention.py", line 148, in __init__
    self.cu_length = Parameter(shape=[batch_size + 1], dtype="int32")
TypeError: can only concatenate tuple (not "int") to tuple
